; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind optnone uwtable
define i32 @add(i32 %arg1, i32 %arg2) #0 {
; JVM:       iload 0
; JVM-NEXT:    iload 1
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 2
; JVM-NEXT:    iload 2
; JVM-NEXT:    dup
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    ireturn
entry:
  %res1 = add i32 %arg1, %arg2
  %res2 = add i32 %arg1, %arg2
  %res  = add i32 %res1, %res2
  ret i32 %res
}

attributes #0 = { nounwind noinline uwtable }

