; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind uwtable
define i32 @fun(i32 %a, i32 %b, i32 %c) #0 {
; JVM:       iload 0
; JVM-NEXT:    iload 1
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 0
; JVM-NEXT:    iload 2
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 4
; JVM-NEXT:    iload 3
; JVM-NEXT:    iload 4
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 5
; JVM-NEXT:    iload 5
; JVM-NEXT:    ldc 21
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 6
; JVM-NEXT:    iload 6
; JVM-NEXT:    ireturn
entry:
  %add = add nsw i32 %a, %b
  %add1 = add nsw i32 %a, %c
  %add2 = add nsw i32 %add, %add1
  %add3 = add nsw i32 %add2, 21
  ret i32 %add3
}

