; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @getValAt(i32 %i) #0 {
; JVM:       iload 0
; JVM-NEXT:    iconst_2
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 1
; JVM-NEXT:    ldc 20
; JVM-NEXT:    newarray byte
; JVM-NEXT:    astore 3
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 1
; JVM-NEXT:    ldc 120
; JVM-NEXT:    bastore
; JVM-NEXT:    iload 1
; JVM-NEXT:    iconst_1
; JVM-NEXT:    ior
; JVM-NEXT:    istore 4
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 4
; JVM-NEXT:    ldc 86
; JVM-NEXT:    bastore
; JVM-NEXT:    iload 1
; JVM-NEXT:    iconst_2
; JVM-NEXT:    ior
; JVM-NEXT:    istore 5
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 5
; JVM-NEXT:    ldc 52
; JVM-NEXT:    bastore
; JVM-NEXT:    iload 1
; JVM-NEXT:    iconst_3
; JVM-NEXT:    ior
; JVM-NEXT:    istore 6
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 6
; JVM-NEXT:    ldc 18
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 1
; JVM-NEXT:    baload
; JVM-NEXT:    istore 7
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 4
; JVM-NEXT:    baload
; JVM-NEXT:    istore 8
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 5
; JVM-NEXT:    baload
; JVM-NEXT:    istore 9
; JVM-NEXT:    iload 9
; JVM-NEXT:    istore 10
; JVM-NEXT:    iload 10
; JVM-NEXT:    ldc 16
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 11
; JVM-NEXT:    aload 3
; JVM-NEXT:    iload 6
; JVM-NEXT:    baload
; JVM-NEXT:    istore 12
; JVM-NEXT:    iload 12
; JVM-NEXT:    istore 13
; JVM-NEXT:    iload 13
; JVM-NEXT:    ldc 24
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 14
; JVM-NEXT:    iload 14
; JVM-NEXT:    iload 11
; JVM-NEXT:    ior
; JVM-NEXT:    istore 15
; JVM-NEXT:    iload 8
; JVM-NEXT:    istore 16
; JVM-NEXT:    iload 16
; JVM-NEXT:    ldc 8
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 17
; JVM-NEXT:    iload 15
; JVM-NEXT:    iload 17
; JVM-NEXT:    ior
; JVM-NEXT:    istore 18
; JVM-NEXT:    iload 7
; JVM-NEXT:    iload 18
; JVM-NEXT:    istore 19
; JVM-NEXT:    iload 19
; JVM-NEXT:    ior
; JVM-NEXT:    istore 20
; JVM-NEXT:    iload 20
; JVM-NEXT:    ireturn
entry:
  %arr = alloca [20 x i8], align 16
  %arraydecay = getelementptr inbounds [20 x i8], [20 x i8]* %arr, i32 0, i32 0
  %0 = bitcast i8* %arraydecay to i32*
  %idxprom = sext i32 %i to i64
  %arrayidx = getelementptr inbounds i32, i32* %0, i64 %idxprom
  store i32 305419896, i32* %arrayidx, align 4
  %idxprom1 = sext i32 %i to i64
  %arrayidx2 = getelementptr inbounds i32, i32* %0, i64 %idxprom1
  %1 = load i32, i32* %arrayidx2, align 4
  ret i32 %1
}

attributes #0 = { noinline nounwind uwtable }
