; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown -jvm-candidate-checker | FileCheck %s --check-prefix=JVM -match-full-lines

%struct.S1 = type <{ i32, i8, [2 x i32], [2 x %struct.S2] }>
%struct.S2 = type <{ i32, [5 x i8], [5 x i32] }>

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @test_struct(%struct.S1* byval align 8 %obj, i32 %index, i32 %val) #0 {
; JVM:       aload 0
; JVM-NEXT:    getfield AoCClass1/f3 [LAoCClass2;
; JVM-NEXT:    bipush 0
; JVM-NEXT:    aaload
; JVM-NEXT:    getfield AoCClass2/f1 [B
; JVM-NEXT:    bipush 4
; JVM-NEXT:    ldc 10
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 0
; JVM-NEXT:    getfield AoCClass1/f3 [LAoCClass2;
; JVM-NEXT:    bipush 0
; JVM-NEXT:    aaload
; JVM-NEXT:    getfield AoCClass2/f2 [I
; JVM-NEXT:    bipush 0
; JVM-NEXT:    iaload
; JVM-NEXT:    istore 1
; JVM-NEXT:    aload 0
; JVM-NEXT:    getfield AoCClass1/f3 [LAoCClass2;
; JVM-NEXT:    bipush 0
; JVM-NEXT:    aaload
; JVM-NEXT:    getfield AoCClass2/f2 [I
; JVM-NEXT:    bipush 0
; JVM-NEXT:    iload 1
; JVM-NEXT:    ldc -16777216
; JVM-NEXT:    iand
; JVM-NEXT:    istore 2
; JVM-NEXT:    iload 2
; JVM-NEXT:    iastore
; JVM-NEXT:    aload 0
; JVM-NEXT:    getfield AoCClass1/f3 [LAoCClass2;
; JVM-NEXT:    bipush 0
; JVM-NEXT:    aaload
; JVM-NEXT:    getfield AoCClass2/f1 [B
; JVM-NEXT:    bipush 4
; JVM-NEXT:    baload
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    aload 0
; JVM-NEXT:    getfield AoCClass1/f3 [LAoCClass2;
; JVM-NEXT:    bipush 0
; JVM-NEXT:    aaload
; JVM-NEXT:    getfield AoCClass2/f2 [I
; JVM-NEXT:    bipush 0
; JVM-NEXT:    iaload
; JVM-NEXT:    istore 4
; JVM-NEXT:    iload 4
; JVM-NEXT:    ldc -256
; JVM-NEXT:    iand
; JVM-NEXT:    istore 5
; JVM-NEXT:    iload 5
; JVM-NEXT:    ldc 8
; JVM-NEXT:    iushr
; JVM-NEXT:    istore 6
; JVM-NEXT:    iload 6
; JVM-NEXT:    istore 7
; JVM-NEXT:    iload 7
; JVM-NEXT:    ior
; JVM-NEXT:    istore 8
; JVM-NEXT:    iload 8
; JVM-NEXT:    ireturn
entry:
  %f3 = getelementptr inbounds %struct.S1, %struct.S1* %obj, i32 0, i32 2
  %0 = bitcast [2 x i32]* %f3 to i32*
  %arrayidx = getelementptr inbounds i32, i32* %0, i64 4
  store i32 10, i32* %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds i32, i32* %0, i64 4
  %1 = load i32, i32* %arrayidx1, align 4
  ret i32 %1
}
attributes #0 = { noinline nounwind uwtable}
