; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown -jvm-candidate-checker | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind
define dso_local signext i16 @getValS(i32 %val) #0 {
; JVM:       iload 0
; JVM-NEXT:    istore 1
; JVM-NEXT:    iload 1
; JVM-NEXT:    ldc -65536
; JVM-NEXT:    iand
; JVM-NEXT:    istore 2
; JVM-NEXT:    iload 2
; JVM-NEXT:    ldc 16
; JVM-NEXT:    iushr
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    i2c
; JVM-NEXT:    istore 4
; JVM-NEXT:    iload 4
; JVM-NEXT:    istore 5
; JVM-NEXT:    iload 5
; JVM-NEXT:    ireturn
entry:
  %val.addr = alloca i32, align 4
  store i32 %val, i32* %val.addr, align 4
  %0 = bitcast i32* %val.addr to i16*
  %arrayidx = getelementptr inbounds i16, i16* %0, i32 1
  %1 = load i16, i16* %arrayidx, align 2
  ret i16 %1
}
attributes #0 = { noinline nounwind }
