; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown -jvm-candidate-checker | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind
define dso_local i32 @getValAt() #0 {
; JVM:       ldc 20
; JVM-NEXT:    newarray byte
; JVM-NEXT:    astore 1
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 0
; JVM-NEXT:    ldc 120
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 1
; JVM-NEXT:    ldc 86
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 2
; JVM-NEXT:    ldc 52
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 3
; JVM-NEXT:    ldc 18
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 0
; JVM-NEXT:    baload
; JVM-NEXT:    istore 2
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 1
; JVM-NEXT:    baload
; JVM-NEXT:    istore 3
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 2
; JVM-NEXT:    baload
; JVM-NEXT:    istore 4
; JVM-NEXT:    iload 4
; JVM-NEXT:    istore 5
; JVM-NEXT:    iload 5
; JVM-NEXT:    ldc 16
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 6
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 3
; JVM-NEXT:    baload
; JVM-NEXT:    istore 7
; JVM-NEXT:    iload 7
; JVM-NEXT:    istore 8
; JVM-NEXT:    iload 8
; JVM-NEXT:    ldc 24
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 9
; JVM-NEXT:    iload 9
; JVM-NEXT:    iload 6
; JVM-NEXT:    ior
; JVM-NEXT:    istore 10
; JVM-NEXT:    iload 3
; JVM-NEXT:    istore 11
; JVM-NEXT:    iload 11
; JVM-NEXT:    ldc 8
; JVM-NEXT:    ishl
; JVM-NEXT:    istore 12
; JVM-NEXT:    iload 10
; JVM-NEXT:    iload 12
; JVM-NEXT:    ior
; JVM-NEXT:    istore 13
; JVM-NEXT:    iload 2
; JVM-NEXT:    iload 13
; JVM-NEXT:    istore 14
; JVM-NEXT:    iload 14
; JVM-NEXT:    ior
; JVM-NEXT:    istore 15
; JVM-NEXT:    iload 15
; JVM-NEXT:    ireturn
entry:
  %arr = alloca [20 x i8], align 1
  %arraydecay = getelementptr inbounds [20 x i8], [20 x i8]* %arr, i32 0, i32 0
  %0 = bitcast i8* %arraydecay to i32*
  %arrayidx = getelementptr inbounds i32, i32* %0, i32 0
  store i32 305419896, i32* %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds i32, i32* %0, i32 0
  %1 = load i32, i32* %arrayidx1, align 4
  ret i32 %1
}
attributes #0 = { noinline nounwind}
