; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown -jvm-candidate-checker | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind
define dso_local signext i8 @getValAt() #0 {
; JVM:       ldc 20
; JVM-NEXT:    newarray byte
; JVM-NEXT:    astore 1
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 0
; JVM-NEXT:    ldc 120
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 1
; JVM-NEXT:    ldc 86
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 2
; JVM-NEXT:    ldc 52
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 3
; JVM-NEXT:    ldc 18
; JVM-NEXT:    bastore
; JVM-NEXT:    aload 1
; JVM-NEXT:    bipush 0
; JVM-NEXT:    baload
; JVM-NEXT:    istore 2
; JVM-NEXT:    iload 2
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    ireturn
entry:
  %arr = alloca [20 x i8], align 1
  %arraydecay = getelementptr inbounds [20 x i8], [20 x i8]* %arr, i32 0, i32 0
  %0 = bitcast i8* %arraydecay to i32*
  %arrayidx = getelementptr inbounds i32, i32* %0, i32 0
  store i32 305419896, i32* %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds [20 x i8], [20 x i8]* %arr, i32 0, i32 0
  %1 = load i8, i8* %arrayidx1, align 1
  ret i8 %1
}
attributes #0 = { noinline nounwind}
