; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM

; Function Attrs: noinline nounwind uwtable
define i32 @doSometing(i32 %arg1, i32 %arg2) #0 {
; JVM:       iload 0
; JVM-NEXT:    iconst_1
; JVM-NEXT:    ldc 0
; JVM-NEXT:    istore 2
; JVM-NEXT:    if_icmplt LBB0_4
; JVM-NEXT:    goto LBB0_1
; JVM-NEXT:  LBB0_1:
; JVM-NEXT:    ldc 0
; JVM-NEXT:    istore 4
; JVM-NEXT:    ldc 0
; JVM-NEXT:    istore 5
; JVM-NEXT:  LBB0_2:
; JVM-NEXT:    iload 5
; JVM-NEXT:    istore 6
; JVM-NEXT:    iload 4
; JVM-NEXT:    istore 7
; JVM-NEXT:    iload 7
; JVM-NEXT:    iload 1
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 8
; JVM-NEXT:    iload 6
; JVM-NEXT:    iload 7
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 9
; JVM-NEXT:    iload 8
; JVM-NEXT:    iload 0
; JVM-NEXT:    iload 8
; JVM-NEXT:    istore 4
; JVM-NEXT:    iload 9
; JVM-NEXT:    istore 5
; JVM-NEXT:    iload 9
; JVM-NEXT:    istore 10
; JVM-NEXT:    if_icmplt LBB0_2
; JVM-NEXT:    goto LBB0_3
; JVM-NEXT:  LBB0_3:
; JVM-NEXT:    iload 10
; JVM-NEXT:    istore 11
; JVM-NEXT:    iload 11
; JVM-NEXT:    istore 2
; JVM-NEXT:  LBB0_4:
; JVM-NEXT:    iload 2
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    ireturn
entry:
  %cmp1 = icmp slt i32 0, %arg1
  br i1 %cmp1, label %for.body.lr.ph, label %for.end

for.body.lr.ph:                                   ; preds = %entry
  br label %for.body

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %i.03 = phi i32 [ 0, %for.body.lr.ph ], [ %add1, %for.body ]
  %result.02 = phi i32 [ 0, %for.body.lr.ph ], [ %add, %for.body ]
  %add = add nsw i32 %result.02, %i.03
  %add1 = add nsw i32 %i.03, %arg2
  %cmp = icmp slt i32 %add1, %arg1
  br i1 %cmp, label %for.body, label %for.end

for.end:                                          ; preds = %for.body, %entry
  %result.0.lcssa = phi i32 [ 0, %entry ], [ %add, %for.body ]
  ret i32 %result.0.lcssa
}

attributes #0 = { noinline nounwind uwtable }
