; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM -match-full-lines

%struct.S1 = type { i32, i32 }

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @main() #0 {
; JVM:       new AoCClass1
; JVM-NEXT:    dup
; JVM-NEXT:    invokenonvirtual AoCClass1/<init>()V
; JVM-NEXT:    astore 2
; JVM-NEXT:    new AoCClass1
; JVM-NEXT:    dup
; JVM-NEXT:    invokenonvirtual AoCClass1/<init>()V
; JVM-NEXT:    astore 4
; JVM-NEXT:    iconst_0
; JVM-NEXT:    istore 0
; JVM-NEXT:    aload 2
; JVM-NEXT:    ldc 269488144
; JVM-NEXT:    putfield AoCClass1/f0 I
; JVM-NEXT:    aload 2
; JVM-NEXT:    ldc 269488144
; JVM-NEXT:    putfield AoCClass1/f1 I
; JVM-NEXT:    aload 2
; JVM-NEXT:    getfield AoCClass1/f0 I
; JVM-NEXT:    istore 5
; JVM-NEXT:    aload 4
; JVM-NEXT:    iload 5
; JVM-NEXT:    putfield AoCClass1/f0 I
; JVM-NEXT:    aload 2
; JVM-NEXT:    getfield AoCClass1/f1 I
; JVM-NEXT:    istore 6
; JVM-NEXT:    aload 4
; JVM-NEXT:    iload 6
; JVM-NEXT:    putfield AoCClass1/f1 I
; JVM-NEXT:    aload 4
; JVM-NEXT:    getfield AoCClass1/f0 I
; JVM-NEXT:    istore 7
; JVM-NEXT:    iload 7
; JVM-NEXT:    ireturn
entry:
  %retval = alloca i32, align 4
  %src = alloca %struct.S1, align 4
  %dst = alloca %struct.S1, align 4
  store i32 0, i32* %retval, align 4
  %0 = bitcast %struct.S1* %src to i8*
  call void @llvm.memset.p0i8.i64(i8* align 4 %0, i8 16, i64 8, i1 false)
  %1 = bitcast %struct.S1* %dst to i8*
  %2 = bitcast %struct.S1* %src to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 %1, i8* align 4 %2, i64 8, i1 false)
  %f1 = getelementptr inbounds %struct.S1, %struct.S1* %dst, i32 0, i32 0
  %3 = load i32, i32* %f1, align 4
  ret i32 %3
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1) #1

; Function Attrs: argmemonly nounwind
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture writeonly, i8* nocapture readonly, i64, i1) #1

attributes #0 = { noinline nounwind uwtable}
