; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM -match-full-lines


; Function Attrs: noinline nounwind uwtable
define dso_local i32 @main() #0 {
; JVM:       ldc 10
; JVM-NEXT:    newarray int
; JVM-NEXT:    astore 2
; JVM-NEXT:    ldc 10
; JVM-NEXT:    newarray int
; JVM-NEXT:    astore 4
; JVM-NEXT:    iconst_0
; JVM-NEXT:    istore 0
; JVM-NEXT:    iconst_0
; JVM-NEXT:    ifne LBB0_4
; JVM-NEXT:    goto LBB0_1
; JVM-NEXT:  LBB0_1:
; JVM-NEXT:    ldc 0
; JVM-NEXT:    istore 5
; JVM-NEXT:  LBB0_2:
; JVM-NEXT:    iload 5
; JVM-NEXT:    istore 6
; JVM-NEXT:    aload 2
; JVM-NEXT:    iload 6
; JVM-NEXT:    ldc 2139062143
; JVM-NEXT:    iastore
; JVM-NEXT:    iload 6
; JVM-NEXT:    iconst_1
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 7
; JVM-NEXT:    iload 7
; JVM-NEXT:    ldc 10
; JVM-NEXT:    iload 7
; JVM-NEXT:    istore 5
; JVM-NEXT:    if_icmplt LBB0_2
; JVM-NEXT:    goto LBB0_3
; JVM-NEXT:  LBB0_3:
; JVM-NEXT:  LBB0_4:
; JVM-NEXT:    ldc2_w 0
; JVM-NEXT:    lstore 8
; JVM-NEXT:  LBB0_5:
; JVM-NEXT:    lload 8
; JVM-NEXT:    lstore 10
; JVM-NEXT:    aload 2
; JVM-NEXT:    lload 10
; JVM-NEXT:    l2i
; JVM-NEXT:    istore 12
; JVM-NEXT:    iload 12
; JVM-NEXT:    iaload
; JVM-NEXT:    istore 13
; JVM-NEXT:    aload 4
; JVM-NEXT:    iload 12
; JVM-NEXT:    iload 13
; JVM-NEXT:    iastore
; JVM-NEXT:    lload 10
; JVM-NEXT:    lconst_1
; JVM-NEXT:    ladd
; JVM-NEXT:    lstore 14
; JVM-NEXT:    lload 14
; JVM-NEXT:    ldc2_w 10
; JVM-NEXT:    lcmp
; JVM-NEXT:    iconst_0
; JVM-NEXT:    lload 14
; JVM-NEXT:    lstore 8
; JVM-NEXT:    if_icmplt LBB0_5
; JVM-NEXT:    goto LBB0_6
; JVM-NEXT:  LBB0_6:
; JVM-NEXT:    aload 4
; JVM-NEXT:    bipush 3
; JVM-NEXT:    iaload
; JVM-NEXT:    istore 17
; JVM-NEXT:    iload 17
; JVM-NEXT:    ireturn
entry:
  %retval = alloca i32, align 4
  %arr_src = alloca [10 x i32], align 16
  %arr_dst = alloca [10 x i32], align 16
  store i32 0, i32* %retval, align 4
  %arraydecay = getelementptr inbounds [10 x i32], [10 x i32]* %arr_src, i32 0, i32 0
  %0 = bitcast i32* %arraydecay to i8*
  call void @llvm.memset.p0i8.i64(i8* align 16 %0, i8 127, i64 40, i1 false)
  %arraydecay1 = getelementptr inbounds [10 x i32], [10 x i32]* %arr_dst, i32 0, i32 0
  %1 = bitcast i32* %arraydecay1 to i8*
  %arraydecay2 = getelementptr inbounds [10 x i32], [10 x i32]* %arr_src, i32 0, i32 0
  %2 = bitcast i32* %arraydecay2 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 16 %1, i8* align 16 %2, i64 40, i1 false)
  %arrayidx = getelementptr inbounds [10 x i32], [10 x i32]* %arr_dst, i64 0, i64 3
  %3 = load i32, i32* %arrayidx, align 4
  ret i32 %3
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1) #1

; Function Attrs: argmemonly nounwind
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture writeonly, i8* nocapture readonly, i64, i1) #1

attributes #0 = { noinline nounwind uwtable}
