; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @main() #0 {
; JVM:       ldc 0
; JVM-NEXT:    ireturn
entry:
  %add = add nsw i32 2, 2
  ret i32 0
}

attributes #0 = { noinline nounwind uwtable}
