; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=jvm32-unknown-unknown -jvm-candidate-checker | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: norecurse nounwind readnone uwtable
define dso_local i32 @getMax(i32 %a, i32 %b) local_unnamed_addr #0 {
; JVM:       iload 0
; JVM-NEXT:    iload 1
; JVM-NEXT:    if_icmple LBB0_2
; JVM-NEXT:    goto LBB0_1
; JVM-NEXT:  LBB0_1:
; JVM-NEXT:    iload 0
; JVM-NEXT:    istore 2
; JVM-NEXT:    goto LBB0_3
; JVM-NEXT:  LBB0_2:
; JVM-NEXT:    iload 1
; JVM-NEXT:    istore 2
; JVM-NEXT:  LBB0_3:
; JVM-NEXT:    iload 2
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    ireturn
entry:
  %cmp = icmp sgt i32 %a, %b
  %cond = select i1 %cmp, i32 %a, i32 %b
  ret i32 %cond
}

attributes #0 = { norecurse nounwind readnone uwtable}
