; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=jvm32-unknown-unknown -jvm-candidate-checker | FileCheck %s --check-prefix=JVM -match-full-lines

; Function Attrs: noinline nounwind uwtable
define dso_local signext i16 @func() #0 {
; JVM:       ldc 2
; JVM-NEXT:    istore 0
; JVM-NEXT:    ldc 4
; JVM-NEXT:    istore 1
; JVM-NEXT:    iload 0
; JVM-NEXT:    iload 1
; JVM-NEXT:    istore 2
; JVM-NEXT:    iload 2
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 4
; JVM-NEXT:    iload 4
; JVM-NEXT:    i2c
; JVM-NEXT:    istore 5
; JVM-NEXT:    iload 5
; JVM-NEXT:    istore 6
; JVM-NEXT:    iload 6
; JVM-NEXT:    ireturn
entry:
  %s1 = alloca i16, align 2
  %s2 = alloca i16, align 2
  store i16 2, i16* %s1, align 2
  store i16 4, i16* %s2, align 2
  %0 = load i16, i16* %s1, align 2
  %conv = sext i16 %0 to i32
  %1 = load i16, i16* %s2, align 2
  %conv1 = sext i16 %1 to i32
  %add = add nsw i32 %conv, %conv1
  %conv2 = trunc i32 %add to i16
  ret i16 %conv2
}
attributes #0 = { noinline nounwind uwtable}
