; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;RUN: llc < %s -mtriple=jvm32-unknown-unknown | FileCheck %s --check-prefix=JVM

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @function(i32 %cond) #0 {
; JVM:       iload 0
; JVM-NEXT:    iconst_2
; JVM-NEXT:    if_icmpeq LBB0_3
; JVM-NEXT:    goto LBB0_6
; JVM-NEXT:  LBB0_6:
; JVM-NEXT:    iload 0
; JVM-NEXT:    iconst_1
; JVM-NEXT:    if_icmpeq LBB0_2
; JVM-NEXT:    goto LBB0_7
; JVM-NEXT:  LBB0_7:
; JVM-NEXT:    iload 0
; JVM-NEXT:    iconst_0
; JVM-NEXT:    if_icmpne LBB0_4
; JVM-NEXT:    goto LBB0_1
; JVM-NEXT:  LBB0_1:
; JVM-NEXT:    ldc 0
; JVM-NEXT:    istore 1
; JVM-NEXT:    goto LBB0_5
; JVM-NEXT:  LBB0_2:
; JVM-NEXT:    ldc 1
; JVM-NEXT:    istore 1
; JVM-NEXT:    goto LBB0_5
; JVM-NEXT:  LBB0_3:
; JVM-NEXT:    ldc 2
; JVM-NEXT:    istore 1
; JVM-NEXT:    goto LBB0_5
; JVM-NEXT:  LBB0_4:
; JVM-NEXT:    ldc 3
; JVM-NEXT:    istore 1
; JVM-NEXT:  LBB0_5:
; JVM-NEXT:    iload 1
; JVM-NEXT:    istore 2
; JVM-NEXT:    iload 2
; JVM-NEXT:    ldc 10
; JVM-NEXT:    iadd
; JVM-NEXT:    istore 3
; JVM-NEXT:    iload 3
; JVM-NEXT:    ireturn
entry:
  switch i32 %cond, label %sw.default [
    i32 0, label %sw.bb
    i32 1, label %sw.bb1
    i32 2, label %sw.bb2
  ]

sw.bb:                                            ; preds = %entry
  br label %sw.epilog

sw.bb1:                                           ; preds = %entry
  br label %sw.epilog

sw.bb2:                                           ; preds = %entry
  br label %sw.epilog

sw.default:                                       ; preds = %entry
  br label %sw.epilog

sw.epilog:                                        ; preds = %sw.default, %sw.bb2, %sw.bb1, %sw.bb
  %val.0 = phi i32 [ 3, %sw.default ], [ 2, %sw.bb2 ], [ 1, %sw.bb1 ], [ 0, %sw.bb ]
  %add = add nsw i32 %val.0, 10
  ret i32 %add
}

attributes #0 = { noinline nounwind uwtable}
